version: '3'
services:

  speaker-server:
    image: speaker-server
    container_name: speaker-server
    build:
      context: ../speaker-server
      dockerfile: Dockerfile
    ports:
      - 8001:80
    networks:
      - proxy

  speaker:
    image: speaker
    container_name: speaker
    build:
      context: ../speaker
      dockerfile: Dockerfile
    ports:
      - 3001:80
    networks:
      - proxy
    depends_on:
      - speaker-server

  proxy:
    image: proxy
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
      - speaker

networks:
  proxy:
