version: '3'

services:
  proxy:
    image: proxy
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - proxy
      - speaker
      - ardigen-github-search
      - hex-ocean-dishes
      - portfolio

networks:
  proxy:
     name: proxy
  speaker:
    name: speaker
    external: true
  ardigen-github-search:
    name: ardigen-github-search
    external: true
  hex-ocean-dishes:
    name: hex-ocean-dishes
    external: true
  portfolio:
    name: portfolio
    external: true