version: '3'
services:

  prime-speaker-server:
    image: prime-speaker-server
    container_name: prime-speaker-server
    build:
      context: ../prime-speaker-service/prime-speaker-server
      dockerfile: Dockerfile
    ports:
      - 8001:80
    networks:
      - proxy

  prime-speaker:
    image: prime-speaker
    container_name: prime-speaker
    build:
      context: ../prime-speaker-service/prime-speaker
      dockerfile: Dockerfile
    ports:
      - 3001:80
    networks:
      - proxy
    depends_on:
      - prime-speaker-server

  proxy:
    image: proxy
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
      - prime-speaker

networks:
  proxy:
