version: '3'

services:
  proxy:
    image: proxy
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - proxy
      - speaker
      - ardigen-github-search
      - hex-ocean
    depends_on:
      - speaker

networks:
  proxy:
  speaker:
  ardigen-github-search:
  hex-ocean-dishes: